services:
  db:
    image: mysql:9.0
    restart: always
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./dbdata:/var/lib/mysql

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
    env_file:
      - .env
    tty: true
    command: ["bash", "./run.sh"]
